apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: consumer-deployment
  pollingInterval: 5
  cooldownPeriod: 20
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: rabbitmq
    metadata:
      host: "amqp://rabbitmq"
      protocol: amqp
      queueName: queue
      mode: QueueLength
      value: "5"
