apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: consumer-deployment
  minReplicaCount: 1  # Sempre manter pelo menos 1 instância em execução
  maxReplicaCount: 5  # Escalar até no máximo 5 instâncias
  triggers:
  - type: rabbitmq
    metadata:
      host: "amqp://rabbitmq"
      protocol: amqp
      queueName: test_q
      mode: QueueLength
      value: "5"
